import React from 'react';

export default () => {
    return (
        <section id="portfolio" className="portfolio section-bg" >
            <div className="container" data-aos="fade-up">

                <div className="section-title">
                    <h2>Projects</h2>
                </div>

                <div className="row portfolio-container" data-aos="fade-up" data-aos-delay="200" >

                    <div className="col-lg-4 col-md-6 portfolio-item filter-app">

                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>Weather App</h3>
                            <p style={{textAlign:'justify'}}>
                            This application has been created using React.js, JavaScript, and Bootstrap. When the user enters the city 
                             it’s corresponding weather conditions are displayed. A Weather API from the OpenWeatherMap was used 
                            to gather information. The information from the API helps in displaying the weather conditions that include overall 
                            temperature, min temperature, max temperature and weather types such as sunny, windy, rainy, cloudy or thunderstorm.
                </p>

                        </div>
                    </div>

                    <div className="col-lg-4 col-md-6 portfolio-item filter-web">
                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>Lets's Talk</h3>
                            <p style={{textAlign:'justify'}}>Lets Talk is a website for people facing mental health issues was
                        created this for hackathon techtoegther2019. Resources can be accessed after a user signs up and fill some details. User centric recommendations are generated based on those details. In
                        apps resource links to various apps are provided to go through. Google books API was integrated with the UI 
                        to give book recommendations. Videos were shown using iframe. Chatbot was created using IBM Watson.</p>

                        </div>
                    </div>


                    <div className="col-lg-4 col-md-6 portfolio-item filter-app">
                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>City Crime Management</h3>
                            <p style={{textAlign:'justify'}}>
                                A swing application was developed wherein a citizen can anonymously report a case. An ecosystem model using a singleton design pattern was demonstrated in this application. Complete
                                data including the cases and locations was stored using the ArrayList and Linked list. Additional features like a pie chart,
                                email and choosing a date were implemented using JFreeChart, JavaMail API and date chooser respectively.
                </p>

                        </div>
                    </div>

                    <div className="col-lg-4 col-md-6 portfolio-item filter-app">
                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>Tennis Game </h3>
                            <p style={{textAlign:'justify'}}>
                                 A single-player game was developed using HTML-5 Canvas. The user can control the racquet movement using the mouse. The score is displayed on the board. If a
                                player misses a ball, the other player gets a point. The player that reaches three points first wins the game. After a
                                point is scored, game control resets and starts from the center. In the end, the winner is displayed on the board.
            </p>
                        </div>
                    </div>

                    <div className="col-lg-4 col-md-6 portfolio-item filter-app">
                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>Hospital Database Management System</h3>
                            <p style={{textAlign:'justify'}}>
                                The project resolved data management problem by applying data queries to efficiently handle database. Built schema based on an entity-relationship diagram with minimum data redundancy. Learned and applied joints, triggers, and stored procedures using MySQL. Analyzed revenue generated by the hospital and the salary of the department.
               </p>

                        </div>
                    </div>

                    <div className="col-lg-4 col-md-6 portfolio-item filter-app">
                        <div className="portfolio-info">
                            <h3 style={{ color: "#0b4cad" }}>Grocery Management System</h3>
                            <p style={{textAlign:'justify'}}>
                                It was built on the concept of Spring MVC. Implemented features such as login of customer and adding item to cart and able to order the items. Managed data of customers information, transactions details and stock of items in table using hibernate and MySQL
                                Blueprinted front–end such as login page, customer and manager page using JSP.
              </p>

                        </div>
                    </div>



                    <div className="col-lg-12 col-md-4 portfolio-item filter-app" style={{ textAlign: 'center' }}>
                        <div className="portfolio-info" style={{ textAlign: 'center' }}>
                            <h3 style={{ color: "#0b4cad" }}>Wait! There's more..</h3>
                            <p>See<a href="https://github.com/KinjalPM" target="_blank" style={{ color: "#0b4cad" }}> all Creations</a> for more examples!</p>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    )
}